export const LOAD_POINT_ROUTES_START = "LOAD_POINT_ROUTES_START";
export const LOAD_POINT_ROUTES_SUCCESS = "LOAD_POINT_ROUTES_SUCCESS";
export const LOAD_POINT_ROUTES_ERROR = "LOAD_POINT_ROUTES_ERROR";
export const LOAD_POINT_ROUTES_CLEAR = "LOAD_POINT_ROUTES_CLEAR";

export const SET_SELECTED_ROUTE = "SET_SELECTED_ROUTE";
export const CLEAR_SELECTED_ROUTE = "CLEAR_SELECTED_ROUTE";
