export const ON_ROUTE_PREVIEW_CANCEL = 'ON_ROUTE_PREVIEW_CANCEL';
export const ON_ROUTE_PREVIEW = 'ON_ROUTE_PREVIEW';
export const SET_ROUTES = 'SET_ROUTES';
export const SET_SEARCH_ROUTES_RESULTS = 'SET_SEARCH_ROUTES_RESULTS';
export const CLEAR_SEARCH_ROUTES_RESULTS = 'CLEAR_SEARCH_ROUTES_RESULTS';
export const SEARCH_ROUTE_ACTIVE = 'SEARCH_ROUTE_ACTIVE';
export const SHOW_BOTTOM_SHEET = 'SHOW_BOTTOM_SHEET';
export const HIDE_BOTTOM_SHEET = 'HIDE_BOTTOM_SHEET';

export const SHOW_BUSES_SHEET = 'SHOW_BUSES_SHEET';
export const HIDE_BUSES_SHEET = 'HIDE_BUSES_SHEET';
