export const ON_ROUTE_PREVIEW_CANCEL = 'ON_ROUTE_PREVIEW_CANCEL';
export const ON_ROUTE_PREVIEW = 'ON_ROUTE_PREVIEW';
export const SET_ROUTES = 'SET_ROUTES';
export const SET_SEARCH_ROUTES_RESULTS = 'SET_SEARCH_ROUTES_RESULTS';
export const CLEAR_SEARCH_ROUTES_RESULTS = 'CLEAR_SEARCH_ROUTES_RESULTS';
export const SEARCH_ROUTE_ACTIVE = 'SEARCH_ROUTE_ACTIVE';
