export const whiteColor = '#ffffff';
export const primaryColor = '#0057FF';
export const secondaryColor = '#FFD353';
export const darkColor = '#000000';
export const lightDark = '#888888';
export const lightGrey = '#4F4F4F';
export const touchableLight = '#f0f0f0';
export const transparent = '#ffffff00';
export const yellowColor ='#FFD447';
